### PR TITLE
[FIX] chown volumen locations to ODOO_USER before defining as volumes

### PR DESCRIPTION
**Pull request by evaldez89**
[FIX] chown the volumen locations to ODOO_USER before defining those locations as volumens #127

### CODE REVIEW

**Comment by evaldez89** [comment]
Results:

https://user-images.githubusercontent.com/12959163/119243469-11217c00-bb35-11eb-973f-fadf49d78c50.mp4

**Comment by gustavovalverde** [comment]
Oh, nice catch 👍🏻 

Could you do this same PR targeting v11? This way I can forward-port it to v14.

Also, please keep changes to a minimum, just move the lines to the right position, without adding `sudo` or removing the comments. 
```dockerfile
# Own folders    //-- docker-compose creates named volumes owned by root:root. Issue: https://github.com/docker/compose/issues/3270
RUN chown -R ${ODOO_USER}:${ODOO_USER} ${ODOO_DATA_DIR} ${ODOO_LOGS_DIR} /etc/odoo
```

**Comment by evaldez89** [comment]
> Oh, nice catch 👍🏻
> 
> Could you do this same PR targeting v11? This way I can forward-port it to v14.
> 
> Also, please keep changes to a minimum, just move the lines to the right position, without adding `sudo` or removing the comments.
> 
> ```dockerfile
> # Own folders    //-- docker-compose creates named volumes owned by root:root. Issue: https://github.com/docker/compose/issues/3270
> RUN chown -R ${ODOO_USER}:${ODOO_USER} ${ODOO_DATA_DIR} ${ODOO_LOGS_DIR} /etc/odoo
> ```

Done

- [ ] do this same PR targeting v11? This way I can forward-port it to v14.
- [ ]  keep changes to a minimum, just move the lines to the right position, without adding sudo or removing the comments

**Comment by andrp92** [comment]
Thanks @evaldez89 

Merged here https://github.com/iterativo-git/dockerdoo/pull/137

**Pull request closed without merging**
